### ISSUE TITLE
Keep getting NoMethodError for method ‘to_local’ when trying to call .in_working_hours?

### ISSUE THREAD

**Issue by uajqq** [Intrepidd/working_hours#40]
I keep getting the following error when trying to use the in_working_hours function:

```
NoMethodError
  5260     undefined method `to_local' for #<TZInfo::TransitionsTimezonePeriod:0x00007fc81095f008>
  5260       /Users/xxx/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/activesupport-3.2.22.5/lib/active_support/time_with_zone.rb:52:in `time'
  5260       /Users/xxx/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/activesupport-3.2.22.5/lib/active_support/time_with_zone.rb:268:in `wday'
  5260       /Users/xxx/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/working_hours-1.2.0/lib/working_hours/computation.rb:147:in `working_day?'
  5260       /Users/xxx/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/working_hours-1.2.0/lib/working_hours/computation.rb:153:in `in_working_hours?'
  5260       /Users/xxx/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/working_hours-1.2.0/lib/working_hours/core_ext/date_and_time.rb:46:in `in_working_hours?'
```

Any ideas? I’ve tried to install/update `activesupport` with no result.

**Comment by uajqq** [comment]
Never mind, I got it resolved by forcing `bundle` to load the most recent version of `activesupport`. Not sure why it wasn’t getting the most recent by default.
